"""
Cannibalization & Cross-Product Relationship Engine.
Handles cross-price elasticity for substitute SKUs and basket affinity for complementary SKUs.
"""

from typing import List, Dict, Tuple
from .models import InventoryItem

class CannibalizationEngine:
    def __init__(self, inventory: List[InventoryItem]):
        self.inventory_map = {item.sku: item for item in inventory}

    def calculate_cannibalization_loss(
        self, promoted_sku: str, discount_pct: float, expected_promo_units: int
    ) -> Tuple[float, List[Dict[str, float]]]:
        """
        Calculates the revenue diverted away from substitute full-margin SKUs when a product is discounted.
        Returns total cannibalization loss ($) and breakdown per affected SKU.
        """
        item = self.inventory_map.get(promoted_sku)
        if not item or not item.substitute_skus:
            return 0.0, []

        total_loss = 0.0
        breakdown = []

        # Discount depth factor (higher discount = higher diversion from substitutes)
        diversion_factor = min(0.45, (discount_pct / 100.0) * 1.2)

        for sub_sku in item.substitute_skus:
            sub_item = self.inventory_map.get(sub_sku)
            if not sub_item:
                continue

            # Estimate lost full-margin sales of substitute
            diverted_units = int(expected_promo_units * diversion_factor * 0.25)
            lost_margin = diverted_units * (sub_item.list_price - sub_item.cost_price)
            
            total_loss += lost_margin
            breakdown.append({
                "affected_sku": sub_sku,
                "affected_name": sub_item.name,
                "lost_units": diverted_units,
                "lost_margin_usd": round(lost_margin, 2)
            })

        return round(total_loss, 2), breakdown

    def calculate_complementary_boost(
        self, promoted_sku: str, expected_promo_units: int
    ) -> Tuple[float, List[Dict[str, float]]]:
        """
        Calculates additional revenue generated by complementary items purchased alongside the promoted SKU.
        """
        item = self.inventory_map.get(promoted_sku)
        if not item or not item.complementary_skus:
            return 0.0, []

        total_boost = 0.0
        breakdown = []

        # Attachment rate (e.g. 35% of laptop buyers buy a mouse/sleeve)
        attach_rate = 0.35

        for comp_sku in item.complementary_skus:
            comp_item = self.inventory_map.get(comp_sku)
            if not comp_item:
                continue

            attached_units = int(expected_promo_units * attach_rate)
            added_profit = attached_units * (comp_item.list_price - comp_item.cost_price)

            total_boost += added_profit
            breakdown.append({
                "boosted_sku": comp_sku,
                "boosted_name": comp_item.name,
                "attached_units": attached_units,
                "added_profit_usd": round(added_profit, 2)
            })

        return round(total_boost, 2), breakdown
